### Site Settings ###
title: Harsh Tiwari
description: >-
  "Enrepreneurial Geek, Coder and can make any ideas into a project."
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: harshvarddhantiwari/harshvarddhantiwari.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)

### Plugins ###
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Harsh Tiwari
  image: assets/harsh-tiwari.jpg
  # behance           : your_username
  # dribbble          : your_username
  email: harshk915@gmail.com
  #facebook: amanroy007
  github: harshvarddhantiwari
  #keybase: amanroy
  # gitlab            : your_username
  # instagram         : your_username
  linkedin: iharshtiwari
  # medium            : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  twitter: imharshhub
# vimeo             : your_username
# youtube           : your_channel_name

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # Set false to disable comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
